version: '3.8'

services:
  db:
    image: mysql:8.0  #
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Ni@12345
      MYSQL_DATABASE: todo_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 12345
    ports:
      - "3306:3306"